# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GoogleJapaneseIME
      directives:
        description: Install Google Japanese IME
        allowPrerelease: true
      settings:
        id: Google.JapaneseIME
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: ExplorerPatcher
      directives:
        description: Install ExplorerPatcher
        allowPrerelease: true
      settings:
        id: valinet.ExplorerPatcher
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WindowsADK
      directives:
        description: Install Windows ADK
        allowPrerelease: true
      settings:
        id: Microsoft.WindowsADK
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerShell
      directives:
        description: Install PowerShell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Biscuit
      directives:
        description: Install Biscuit
        allowPrerelease: true
      settings:
        id: Biscuit.Biscuit
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WingetUIStore
      directives:
        description: Install WingetUIStore
        allowPrerelease: true
      settings:
        id: SomePythonThings.WingetUIStore
        source: winget
  configurationVersion: 0.2.0
