# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GoogleJapaneseIME
      directives:
        description: Install Google Japanese IME
        allowPrerelease: true
      settings:
        id: Google.JapaneseIME
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerShell
      directives:
        description: Install PowerShell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Biscuit
      directives:
        description: Install Biscuit
        allowPrerelease: true
      settings:
        id: Biscuit.Biscuit
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GoogleChrome
      directives:
        description: Install Google Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Firefox
      directives:
        description: Install Firefox
        allowPrerelease: true
      settings:
        id: Mozilla.Firefox
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: PowerToys
      directives:
        description: Install PowerToys
        allowPrerelease: true
      settings:
        id: Microsoft.Powertoys
        source: winget
        scope: machine
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: bitwarden
      directives:
        description: Install Bitwarden
        allowPrerelease: false
      settings:
        id: 8bitSolutionsLLC.Bitwarden
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Honeyview
      directives:
        description: Install Honeyview
        allowPrerelease: false
      settings:
        id: Bandisoft.Honeyview
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Everything
      directives:
        description: Install Everything
        allowPrerelease: false
      settings:
        id: voidtools.Everything
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: sumatrapdf
      directives:
        description: Install SumatraPDF
        allowPrerelease: false
      settings:
        id: SumatraPDF.SumatraPDF
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: teraterm
      directives:
        description: Install Tera Term
        allowPrerelease: false
      settings:
        id: TeraTermProject.teraterm5
        source: winget
configurationVersion: 0.2.0
