# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: GeForceExperience
      directives:
        description: Install GeForce Experience
        allowPrerelease: true
      settings:
        id: NVIDIA.GeForceExperience
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: LinkShellExtension
      directives:
        description: Install Link Shell Extension
        allowPrerelease: true
      settings:
        id: HermannSchinagl.LinkShellExtension
        source: winget
  configurationVersion: 0.2.0
